export const instantLabs = [
  'CBC with Differential',
  'Basic Metabolic Panel (BMP)',
  'Comprehensive Metabolic Panel (CMP)',
  'Magnesium',
  'Phosphorus',
  'Calcium, Total',
  'Calcium, Ionized',
  'Liver Function Panel',
  'Coagulation: PT/INR',
  'Coagulation: aPTT',
  'Fibrinogen',
  'D-dimer',
  'ABG with Co-oximetry',
  'VBG',
  'Lactate (Serum)',
  'Arterial Lactate Repeat',
  'Troponin High-Sensitivity — Now',
  'Troponin — Repeat 3 Hours',
  'BNP/NT-proBNP',
  'CK Total',
  'CK-MB (if available)',
  'CRP',
  'ESR',
  'Procalcitonin',
  'C. difficile PCR/Toxin',
  'MRSA Nares Screen',
  'Respiratory Pathogen Panel PCR',
  'COVID-19 PCR (Nasopharyngeal)',
  'Influenza A/B PCR',
  'RSV PCR',
  'Urine Legionella Antigen',
  'Urine Strep pneumo Antigen',
  'Stool Culture and Ova/Parasites',
  'Stool Pathogen PCR Panel',
  'Thyroid: TSH',
  'Thyroid: Free T4',
  'Thyroid: Total T3',
  'Vitamin B12',
  'Folate',
  'Vitamin D 25-OH',
  'Iron, TIBC, Ferritin Panel',
  'Lipid Panel — Fasting',
  'Hemoglobin A1c',
  'Glucose POC',
  'Serum Osmolality',
  'Urine Osmolality',
  'Urinalysis with Microscopy',
  'Urine Sodium/Creatinine',
  'Random Urine Protein/Creatinine Ratio',
  'Urine Ketones',
  'Beta-hydroxybutyrate',
  'Toxicology Screen — Urine',
  'Serum Alcohol Level',
  'Acetaminophen Level',
  'Salicylate Level',
  'Digoxin Level',
  'Lithium Level',
  'Vancomycin Trough',
  'Vancomycin Peak (if ordered)',
  'Aminoglycoside Level',
  'Antiepileptic Drug Level — Levetiracetam',
  'Antiepileptic Drug Level — Valproate',
  'Antiepileptic Drug Level — Phenytoin (Total)',
  'Phenytoin Free Level',
  'Methotrexate Level + Leucovorin Protocol',
  'Complement C3/C4',
  'HIV 1/2 Ag/Ab Screen',
  'Hepatitis B Surface Antigen',
  'Hepatitis B Surface Antibody',
  'Hepatitis C Antibody',
  'Blood Type & Screen',
  'Type & Crossmatch 2 Units PRBC',
  'Prepare FFP 2 Units',
  'Prepare Platelets 1 Apheresis Unit',
  'DAT (Coombs) Test',
  'Haptoglobin',
  'LDH',
  'Reticulocyte Count',
  'Peripheral Smear Review',
  'CSF Cell Count with Differential',
  'CSF Protein/Glucose',
  'CSF Gram Stain',
  'Lipase',
  'Amylase',
  'Pancreatic Fecal Elastase',
  'Fecal Occult Blood Test',
  'Ammonia Level',
  'Ketone Beta-Hydroxybutyrate',
];

export const pendingLabs = [
  'Anti-Xa Level (LMWH)',
  'Heparin-Induced Thrombocytopenia Panel',
  'Antithrombin III',
  'Lupus Anticoagulant Panel',
  'Blood Culture x2 (Peripheral)',
  'Line Sepsis Workup (Line + Peripheral)',
  'Urine Culture',
  'Sputum Culture & Gram Stain',
  'Wound Culture with Gram Stain',
  'AFB Smear',
  'Fungal Culture (Blood)',
  'Anaerobic Blood Culture Bottles',
  'Cortisol AM',
  'ACTH',
  'Prolactin',
  'LH/FSH',
  'Estradiol',
  'Testosterone Total',
  'PTH Intact',
  'PTH-related Peptide (PTHrP)',
  '24-hr Urine Protein Collection',
  'Tacrolimus Level (FK506)',
  'Cyclosporine Level',
  'Sirolimus Level',
  'ANA with Reflex',
  'Rheumatoid Factor',
  'Anti-CCP',
  'dsDNA Antibody',
  'ENA Panel',
  'Thrombophilia Panel (Inherited)',
  'Syphilis Screen (RPR/TPPA)',
  'CMV PCR Quantitative',
  'EBV PCR Quantitative',
  'BK Virus PCR (Urine)',
  'Pathology: Surgical Specimen — Send',
  'Pathology: Cytology — Pleural Fluid',
  'Pathology: Cytology — Ascitic Fluid',
  'Pathology: Cytology — CSF',
  'Pathology: Fine Needle Aspiration',
  'CSF Culture',
  'CSF Meningitis/Encephalitis PCR Panel',
  'Fecal Calprotectin',
  'Serum Protein Electrophoresis (SPEP)',
  'Urine Protein Electrophoresis (UPEP)',
  'Serum Free Light Chains',
  'Beta-2 Microglobulin',
  'Insulin, C-Peptide (Hypoglycemia eval)',
  'Copper Level',
  'Ceruloplasmin',
  'Zinc Level',
  'Lead Level (Adult)',
  'Lead Level (Pediatric)',
  'HLA-B*57:01 (Abacavir)',
  'HLA-B*27 (Spondyloarthropathy)',
];

export const labTypeByName = new Map<string, 'instant' | 'pending'>();

[...instantLabs, ...pendingLabs].forEach((name) => {
  labTypeByName.set(name, instantLabs.includes(name) ? 'instant' : 'pending');
});
