import type { Patient, LabResult, VitalSigns, MedicalOrder } from './types';

export const mockPatients: Patient[] = [
  {
    id: '1',
    roomId: null,
    mrn: '1001234',
    firstName: 'Felix',
    lastName: 'Jones',
    dateOfBirth: '1987-03-15',
    gender: 'Male',
    room: '116',
    service: 'Internal Medicine',
    admissionDate: '2025-09-26',
    attendingPhysician: 'Dr. Smith',
    allergies: ['NKDA'],
    codeStatus: 'Full Code',
  },
  {
    id: '2',
    roomId: null,
    mrn: '1001235',
    firstName: 'Sarah',
    lastName: 'Wilson',
    dateOfBirth: '1992-07-22',
    gender: 'Female',
    room: '118',
    service: 'Internal Medicine',
    admissionDate: '2025-09-27',
    attendingPhysician: 'Dr. Johnson',
    allergies: ['Penicillin', 'Shellfish'],
    codeStatus: 'Full Code',
  },
  {
    id: '3',
    roomId: null,
    mrn: '1001236',
    firstName: 'Robert',
    lastName: 'Davis',
    dateOfBirth: '1965-11-08',
    gender: 'Male',
    room: '119',
    service: 'Internal Medicine',
    admissionDate: '2025-09-25',
    attendingPhysician: 'Dr. Brown',
    allergies: ['Sulfa'],
    codeStatus: 'DNR',
  },
];

export const mockLabResults: LabResult[] = [
  {
    id: '1',
    patientId: '1',
    testName: 'Hemoglobin',
    value: 8.7,
    unit: 'g/dL',
    referenceRange: '12.0-15.5',
    status: 'Abnormal',
    collectionTime: '2025-09-28T05:17:00Z',
    resultTime: '2025-09-28T06:45:00Z',
    orderedBy: 'Dr. Smith',
  },
  {
    id: '2',
    patientId: '1',
    testName: 'White Blood Cell Count',
    value: 12.5,
    unit: 'K/uL',
    referenceRange: '4.0-11.0',
    status: 'Abnormal',
    collectionTime: '2025-09-28T05:17:00Z',
    resultTime: '2025-09-28T06:45:00Z',
    orderedBy: 'Dr. Smith',
  },
  {
    id: '3',
    patientId: '1',
    testName: 'Creatinine',
    value: 1.2,
    unit: 'mg/dL',
    referenceRange: '0.7-1.3',
    status: 'Normal',
    collectionTime: '2025-09-28T05:17:00Z',
    resultTime: '2025-09-28T06:45:00Z',
    orderedBy: 'Dr. Smith',
  },
];

export const mockVitals: VitalSigns[] = [
  {
    id: '1',
    patientId: '1',
    timestamp: '2025-09-28T08:00:00Z',
    temperature: 98.6,
    bloodPressureSystolic: 128,
    bloodPressureDiastolic: 82,
    heartRate: 78,
    respiratoryRate: 16,
    oxygenSaturation: 98,
    pain: 3,
  },
  {
    id: '2',
    patientId: '1',
    timestamp: '2025-09-28T12:00:00Z',
    temperature: 99.1,
    bloodPressureSystolic: 135,
    bloodPressureDiastolic: 88,
    heartRate: 85,
    respiratoryRate: 18,
    oxygenSaturation: 97,
    pain: 4,
  },
];

export const mockOrders: MedicalOrder[] = [
  {
    id: '1',
    patientId: '1',
    category: 'Lab',
    orderName: 'Complete Blood Count',
    priority: 'Routine',
    status: 'Active',
    orderedBy: 'Dr. Smith',
    orderTime: '2025-09-28T06:00:00Z',
    scheduledTime: '2025-09-29T05:00:00Z',
  },
  {
    id: '2',
    patientId: '1',
    category: 'Medication',
    orderName: 'Lisinopril',
    dose: '10mg',
    route: 'PO',
    frequency: 'Daily',
    priority: 'Routine',
    status: 'Active',
    orderedBy: 'Dr. Smith',
    orderTime: '2025-09-27T10:00:00Z',
  },
];
